package tablas;
// Generated 8/03/2016 11:00:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Codigos generated by hbm2java
 */
@Entity
@Table(name="codigos"
    ,schema="public"
)
public class Codigos  implements java.io.Serializable {


     private int idCodigo;
     private Usuario usuario;
     private String dispositivo;
     private Date fecha;

    public Codigos() {
    }

	
    public Codigos(int idCodigo) {
        this.idCodigo = idCodigo;
    }
    public Codigos(int idCodigo, Usuario usuario, String dispositivo, Date fecha) {
       this.idCodigo = idCodigo;
       this.usuario = usuario;
       this.dispositivo = dispositivo;
       this.fecha = fecha;
    }
   
     @Id 

    
    @Column(name="idCodigo", nullable=false)
    public int getIdCodigo() {
        return this.idCodigo;
    }
    
    public void setIdCodigo(int idCodigo) {
        this.idCodigo = idCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="correo")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="dispositivo")
    public String getDispositivo() {
        return this.dispositivo;
    }
    
    public void setDispositivo(String dispositivo) {
        this.dispositivo = dispositivo;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="fecha", length=21)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


