package tablas;
// Generated 8/03/2016 11:00:47 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private String correo;
     private Serializable contrasena;
     private Set codigoses = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String correo) {
        this.correo = correo;
    }
    public Usuario(String correo, Serializable contrasena, Set codigoses) {
       this.correo = correo;
       this.contrasena = contrasena;
       this.codigoses = codigoses;
    }
   
     @Id 

    
    @Column(name="correo", unique=true, nullable=false)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="contrasena")
    public Serializable getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(Serializable contrasena) {
        this.contrasena = contrasena;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getCodigoses() {
        return this.codigoses;
    }
    
    public void setCodigoses(Set codigoses) {
        this.codigoses = codigoses;
    }




}


